"""BoneForge Task Board — Task model and armature check functions.

Each check_* function accepts a single armature bpy.types.Object and
returns a (possibly empty) list of BF_Task instances.  The analyzer
calls all checks and merges the results.

Impact  1–10: quality / correctness improvement if the task is completed.
Effort  1–5:  user effort required (1 = one operator click, 5 = manual work).
Quick-win score = impact / effort — used to rank the top-3 Quick Win cards.
"""

import bpy
import logging

from boneforge.i18n import T

logger = logging.getLogger(__name__)

# ── Category constants ────────────────────────────────────────

CATEGORY_GEOMETRY    = "geometry"
CATEGORY_SKINNING    = "skinning"
CATEGORY_RIG_CONTROLS = "rig_controls"
CATEGORY_FACE_RIG    = "face_rig"
CATEGORY_VRCHAT      = "vrchat"

CATEGORY_ORDER = (
    CATEGORY_RIG_CONTROLS,
    CATEGORY_SKINNING,
    CATEGORY_GEOMETRY,
    CATEGORY_FACE_RIG,
    CATEGORY_VRCHAT,
)

CATEGORY_LABELS = {
    CATEGORY_GEOMETRY:     "Geometry",
    CATEGORY_SKINNING:     "Skinning",
    CATEGORY_RIG_CONTROLS: "Rig Controls",
    CATEGORY_FACE_RIG:     "Face Rig",
    CATEGORY_VRCHAT:       "VRChat",
}

CATEGORY_ICONS = {
    CATEGORY_GEOMETRY:     "MESH_DATA",
    CATEGORY_SKINNING:     "MOD_SKIN",
    CATEGORY_RIG_CONTROLS: "ARMATURE_DATA",
    CATEGORY_FACE_RIG:     "FACE_MAPS",
    CATEGORY_VRCHAT:       "WORLD",
}

# ── Status constants ──────────────────────────────────────────

STATUS_ERROR      = "error"       # Blocks correct deformation
STATUS_WARNING    = "warning"     # Degrades quality noticeably
STATUS_SUGGESTION = "suggestion"  # Optional improvement

STATUS_ICONS = {
    STATUS_ERROR:      "ERROR",
    STATUS_WARNING:    "FUND",
    STATUS_SUGGESTION: "LIGHT",
}

# ── Threshold constants ───────────────────────────────────────

# Bone names that indicate a twist bone is present (Rigify convention).
_TWIST_SUFFIXES = (".twist", "_twist", "-twist", "twist.")
_TWIST_BONE_SUBSTRINGS = ("twist",)

# Rigify limb bones that *should* have associated twist bones.
_LIMBS_NEEDING_TWIST = {
    "upper_arm.L", "upper_arm.R",
    "forearm.L",   "forearm.R",
    "thigh.L",     "thigh.R",
    "shin.L",      "shin.R",
}

# VRChat bone count limits per performance rank.
_VRCHAT_BONE_LIMITS = {
    "Excellent": 75,
    "Good":      150,
    "Medium":    256,
    "Poor":      400,
}

# Weight quality score threshold (mirrors skin_gen.py QUALITY_SCORE_ACCEPTABLE).
_WEIGHT_QUALITY_ACCEPTABLE = 0.65
_WEIGHT_QUALITY_PRODUCTION = 0.85

# Minimum vertex group influence considered non-zero.
_MIN_WEIGHT = 1e-4


# ── Task dataclass ────────────────────────────────────────────

class BF_Task:
    """A single actionable item in the Task Board.

    Using __slots__ keeps memory overhead low when many tasks are cached.
    """
    __slots__ = (
        "task_id", "title", "description", "category", "status",
        "impact", "effort", "operator", "operator_text", "operator_props",
    )

    def __init__(
        self,
        task_id,
        title,
        description,
        category,
        status,
        impact=5,
        effort=3,
        operator=None,
        operator_text="Fix",
        operator_props=None,
    ):
        self.task_id       = task_id
        self.title         = title
        self.description   = description
        self.category      = category
        self.status        = status
        self.impact        = impact
        self.effort        = effort
        self.operator      = operator
        self.operator_text = operator_text
        self.operator_props = operator_props or {}

    @property
    def quick_win_score(self):
        """Higher = better quick win (high impact, low effort)."""
        return self.impact / max(self.effort, 1)

    @property
    def icon(self):
        return STATUS_ICONS.get(self.status, "DOT")


# ── Helper utilities ──────────────────────────────────────────

def _has_twist_bones(armature_obj):
    """Return True if any bone in the armature has a twist-bone name."""
    for bone in armature_obj.data.bones:
        name_lower = bone.name.lower()
        if any(sub in name_lower for sub in _TWIST_BONE_SUBSTRINGS):
            return True
    return False


def _bone_names(armature_obj):
    return {b.name for b in armature_obj.data.bones}


def _get_boneforge_quality_score(armature_obj):
    """Read the cached BoneForge skin quality score from the armature.

    skin_gen.py stores the result as a custom property.  Returns None if
    no score is present (rig wasn't generated by BoneForge skin_gen).
    """
    try:
        return float(armature_obj.get("boneforge_skin_quality", None))
    except (TypeError, ValueError):
        return None


def _get_vrchat_performance_rank(armature_obj):
    """Read the cached VRChat performance rank string from the armature."""
    return armature_obj.get("boneforge_vrchat_rank", None)


def _count_deform_bones(armature_obj):
    return sum(1 for b in armature_obj.data.bones if b.use_deform)


def _mesh_children(armature_obj):
    """Return mesh children of armature_obj that use it via an Armature modifier.

    Searches armature_obj.children (O(direct children)) rather than
    bpy.data.objects (O(all scene objects)) — faster on large scenes.
    """
    return [
        obj for obj in armature_obj.children
        if obj.type == 'MESH'
        and any(
            m.type == 'ARMATURE' and m.object == armature_obj
            for m in obj.modifiers
        )
    ]


# ── Check functions ───────────────────────────────────────────
# Each returns list[BF_Task].  Safe to call on any armature object.

def check_twist_bones(armature_obj):
    """Detect missing twist/roll bones on limb segments."""
    tasks = []
    bones = _bone_names(armature_obj)
    missing_limbs = _LIMBS_NEEDING_TWIST & bones  # limbs that exist in this rig

    if not missing_limbs:
        return tasks  # No Rigify limbs — not a humanoid rig, skip.

    if not _has_twist_bones(armature_obj):
        tasks.append(BF_Task(
            task_id="twist_bones_missing",
            title="Twist bones missing",
            description=(
                "Forearm and upper-arm rotation will produce a 'candy-wrapper' "
                "artifact without twist bones.  Add them via Rig Controls → "
                "Twist Bone Generator."
            ),
            category=CATEGORY_RIG_CONTROLS,
            status=STATUS_ERROR,
            impact=9,
            effort=2,
            operator="boneforge.generate_twist_bones",
            operator_text=T("Generate twist bones"),
        ))
    return tasks


def check_ik_pole_targets(armature_obj):
    """Detect IK chains that lack a pole target (causes flipping)."""
    tasks = []
    if armature_obj.mode not in ('OBJECT', 'POSE'):
        return tasks

    missing_poles = []
    try:
        for pbone in armature_obj.pose.bones:
            for con in pbone.constraints:
                if con.type == 'IK' and con.pole_target is None and con.chain_count >= 2:
                    missing_poles.append(pbone.name)
    except Exception as exc:
        logger.debug(f"check_ik_pole_targets: pose data unavailable: {exc}")

    if missing_poles:
        tasks.append(BF_Task(
            task_id="ik_no_pole_targets",
            title=f"IK chains without pole targets ({len(missing_poles)})",
            description=(
                "IK chains with no pole target can flip unpredictably during "
                "animation.  Add a pole target or use BoneForge Space Switch to "
                "set a stable pole."
            ),
            category=CATEGORY_RIG_CONTROLS,
            status=STATUS_WARNING,
            impact=6,
            effort=3,
        ))
    return tasks


def check_weight_quality(armature_obj):
    """Surface the BoneForge skin quality score as a task when below threshold."""
    tasks = []
    score = _get_boneforge_quality_score(armature_obj)
    if score is None:
        return tasks  # Rig wasn't produced by BoneForge skin_gen — skip.

    if score < _WEIGHT_QUALITY_ACCEPTABLE:
        tasks.append(BF_Task(
            task_id="weight_quality_low",
            title=f"Skin weight quality low ({score:.0%})",
            description=(
                "BoneForge detected weight discontinuities that will cause "
                "visible deformation artefacts.  Run corrective presets or "
                "use Weight Tools to smooth problem areas."
            ),
            category=CATEGORY_SKINNING,
            status=STATUS_ERROR,
            impact=8,
            effort=2,
            operator="boneforge.apply_corrective_presets",
            operator_text=T("Apply corrective presets"),
        ))
    elif score < _WEIGHT_QUALITY_PRODUCTION:
        tasks.append(BF_Task(
            task_id="weight_quality_acceptable",
            title=f"Skin weights need touch-up ({score:.0%})",
            description=(
                "Weights are acceptable but below production quality.  "
                "Use the Weight Table to review and manually adjust problem areas."
            ),
            category=CATEGORY_SKINNING,
            status=STATUS_WARNING,
            impact=5,
            effort=4,
            operator="boneforge.open_weight_table",
            operator_text=T("Open Weight Table"),
        ))
    return tasks


def check_unweighted_vertices(armature_obj):
    """Check if any skinned mesh has vertices with zero total weight."""
    tasks = []
    for mesh_obj in _mesh_children(armature_obj):
        try:
            vg_names = {vg.name for vg in mesh_obj.vertex_groups}
            deform_bones = {
                b.name for b in armature_obj.data.bones
                if b.use_deform and b.name in vg_names
            }
            if not deform_bones:
                continue

            unweighted = 0
            for vert in mesh_obj.data.vertices:
                total = sum(
                    g.weight for g in vert.groups
                    if mesh_obj.vertex_groups[g.group].name in deform_bones
                    and g.weight > _MIN_WEIGHT
                )
                if total < _MIN_WEIGHT:
                    unweighted += 1

            if unweighted > 0:
                ratio = unweighted / max(len(mesh_obj.data.vertices), 1)
                tasks.append(BF_Task(
                    task_id=f"unweighted_verts_{mesh_obj.name}",
                    title=f"Unweighted vertices on '{mesh_obj.name}' ({unweighted})",
                    description=(
                        f"{unweighted} vertices ({ratio:.1%}) have no bone influence "
                        "and will not deform.  Use Weight Tools → Paint or Weight "
                        "Transfer to assign them."
                    ),
                    category=CATEGORY_SKINNING,
                    status=STATUS_WARNING,
                    impact=7,
                    effort=3,
                    operator="boneforge.weight_transfer",
                    operator_text=T("Weight Transfer"),
                ))
        except Exception as exc:
            logger.debug(f"check_unweighted_vertices: skipped {mesh_obj.name}: {exc}")
    return tasks


def check_rig_validator(armature_obj):
    """Run the BoneForge rig validator and surface errors/warnings as tasks."""
    tasks = []
    try:
        from boneforge.advanced_rigging.rig_validator import (
            check_naming,
            check_zero_scale_bones,
            check_weight_sums,
        )
        results = []
        results += check_naming(armature_obj)
        results += check_zero_scale_bones(armature_obj)
        for mesh_obj in _mesh_children(armature_obj):
            results += check_weight_sums(armature_obj, mesh_obj)

        errors   = [r for r in results if r.status == "fail"]
        warnings = [r for r in results if r.status == "warn"]

        if errors:
            tasks.append(BF_Task(
                task_id="validator_errors",
                title=f"Rig validation errors ({len(errors)})",
                description=(
                    f"{len(errors)} validation error(s) detected: "
                    f"{errors[0].message[:80]}{'…' if len(errors[0].message) > 80 else ''}. "
                    "Open Health Check for the full report."
                ),
                category=CATEGORY_RIG_CONTROLS,
                status=STATUS_ERROR,
                impact=8,
                effort=2,
                operator="boneforge.open_health_check",
                operator_text=T("Open Health Check"),
            ))
        elif warnings:
            tasks.append(BF_Task(
                task_id="validator_warnings",
                title=f"Rig validation warnings ({len(warnings)})",
                description=(
                    f"{len(warnings)} warning(s) flagged. "
                    "Open Health Check to review and fix."
                ),
                category=CATEGORY_RIG_CONTROLS,
                status=STATUS_WARNING,
                impact=5,
                effort=2,
                operator="boneforge.open_health_check",
                operator_text=T("Open Health Check"),
            ))
    except ImportError:
        pass
    except Exception as exc:
        logger.debug(f"check_rig_validator: {exc}")
    return tasks


def check_face_rig(armature_obj):
    """Detect if the rig lacks a face rig when a face mesh is present."""
    tasks = []
    bones = _bone_names(armature_obj)

    # Detect face rig by looking for BoneForge face control bone conventions.
    face_control_names = {"eye.L", "eye.R", "jaw_master", "brow.L", "brow.R"}
    has_face_controls = bool(face_control_names & bones)

    # Check if any child mesh has face-region vertices (proxy: has shape keys).
    has_face_mesh = any(
        obj.data.shape_keys is not None
        for obj in _mesh_children(armature_obj)
        if obj.type == 'MESH'
    )

    # Also check head bone as proxy for humanoid rig.
    has_head_bone = "head" in bones

    if has_head_bone and not has_face_controls:
        tasks.append(BF_Task(
            task_id="face_rig_missing",
            title="No face rig detected",
            description=(
                "This rig has a head bone but no facial controls.  "
                "Run the Auto-Rig Wizard with 'Body + Face' to generate "
                "facial bones and shape keys."
            ),
            category=CATEGORY_FACE_RIG,
            status=STATUS_SUGGESTION,
            impact=6,
            effort=2,
            operator="boneforge.autorig_wizard_start",
            operator_text=T("Open Auto-Rig Wizard"),
        ))
    elif has_face_controls and has_face_mesh:
        # Check shape key count — fewer than 9 suggests incomplete face rig.
        for obj in _mesh_children(armature_obj):
            if obj.type == 'MESH' and obj.data.shape_keys:
                sk_count = len(obj.data.shape_keys.key_blocks)
                if sk_count < 9:
                    tasks.append(BF_Task(
                        task_id=f"face_shapekeys_low_{obj.name}",
                        title=f"Face shape keys incomplete ({sk_count}/9)",
                        description=(
                            f"'{obj.name}' has only {sk_count} shape keys.  "
                            "Re-run Face Rig generation or add shape keys "
                            "manually via Correctives."
                        ),
                        category=CATEGORY_FACE_RIG,
                        status=STATUS_WARNING,
                        impact=5,
                        effort=3,
                    ))
                    break
    return tasks


def check_mixamo_bone_names(armature_obj):
    """Detect Mixamo-prefixed bone names and offer to convert them."""
    tasks = []
    mixamo_bones = [
        b.name for b in armature_obj.data.bones
        if b.name.startswith("mixamorig:")
    ]
    if mixamo_bones:
        tasks.append(BF_Task(
            task_id="mixamo_names_detected",
            title=f"Mixamo bone names detected ({len(mixamo_bones)} bones)",
            description=(
                "Mixamo-prefixed names will prevent Rigify, BoneForge Phase 2, "
                "and VRChat humanoid mapping from working correctly.  "
                "Use Retarget → Convert Names to remap to Rigify convention."
            ),
            category=CATEGORY_RIG_CONTROLS,
            status=STATUS_WARNING,
            impact=7,
            effort=1,
            operator="boneforge.retarget_convert_names",
            operator_text=T("Convert Mixamo names"),
        ))
    return tasks


def check_vrchat_performance(armature_obj):
    """Surface VRChat performance rank when it is below Good."""
    tasks = []
    rank = _get_vrchat_performance_rank(armature_obj)
    if rank is None:
        # No cached rank — offer to run the check.
        deform_count = _count_deform_bones(armature_obj)
        if deform_count > _VRCHAT_BONE_LIMITS["Good"]:
            tasks.append(BF_Task(
                task_id="vrchat_rank_unchecked",
                title=f"High bone count may hurt VRChat rank ({deform_count} bones)",
                description=(
                    f"{deform_count} deform bones exceeds the VRChat 'Good' limit "
                    f"({_VRCHAT_BONE_LIMITS['Good']}).  Run the VRChat Performance "
                    "Optimizer to check your rank."
                ),
                category=CATEGORY_VRCHAT,
                status=STATUS_WARNING,
                impact=6,
                effort=2,
                operator="boneforge.run_performance_check",
                operator_text=T("Check VRChat performance"),
            ))
    elif rank in ("Medium", "Poor", "Very Poor"):
        limit = _VRCHAT_BONE_LIMITS.get(rank, 400)
        tasks.append(BF_Task(
            task_id="vrchat_rank_low",
            title=f"VRChat performance rank: {rank}",
            description=(
                f"Your avatar's VRChat performance is '{rank}'.  "
                "Use VRChat → Performance Optimizer to reduce bone count "
                "and mesh complexity."
            ),
            category=CATEGORY_VRCHAT,
            status=STATUS_WARNING,
            impact=7,
            effort=3,
            operator="boneforge.run_performance_optimizer",
            operator_text=T("Open Performance Optimizer"),
        ))
    return tasks


def check_physbone_hair(armature_obj):
    """Suggest PhysBone setup when hair bones are detected but not configured."""
    tasks = []
    hair_keywords = ("hair", "skirt", "tail", "ear", "cloth")
    hair_bones = [
        b.name for b in armature_obj.data.bones
        if any(kw in b.name.lower() for kw in hair_keywords)
    ]
    if not hair_bones:
        return tasks

    # Check if VRChat PhysBone data is stored on the armature.
    has_physbone_data = armature_obj.get("boneforge_physbone_chains") is not None
    if not has_physbone_data:
        tasks.append(BF_Task(
            task_id="physbone_not_configured",
            title=f"Hair/cloth bones need PhysBone setup ({len(hair_bones)} bones)",
            description=(
                f"{len(hair_bones)} bone(s) look like dynamic chains but have no "
                "VRChat PhysBone configuration.  Use VRChat → Hair → "
                "Generate PhysBones to add secondary motion."
            ),
            category=CATEGORY_VRCHAT,
            status=STATUS_SUGGESTION,
            impact=5,
            effort=2,
            operator="boneforge.generate_hair_physbones",
            operator_text=T("Generate PhysBones"),
        ))
    return tasks


def check_space_switch_missing(armature_obj):
    """Suggest space switching on hand/foot IK bones if not yet configured."""
    tasks = []
    ik_targets = {"hand.L", "hand.R", "foot.L", "foot.R"}
    bones = _bone_names(armature_obj)
    ik_present = ik_targets & bones
    if not ik_present:
        return tasks

    # Check for existing Child Of constraints (space switch signature).
    try:
        has_space_switch = any(
            any(c.type == 'CHILD_OF' for c in armature_obj.pose.bones[b].constraints)
            for b in ik_present
            if b in armature_obj.pose.bones
        )
    except Exception as exc:
        logger.debug(f"check_space_switch_missing: pose data unavailable: {exc}")
        return tasks

    if not has_space_switch:
        tasks.append(BF_Task(
            task_id="space_switch_suggested",
            title="IK hands/feet have no space switching",
            description=(
                "Hand and foot IK targets without space switching are locked to "
                "world space.  Add space switches via right-click → "
                "Add Space Switch, or Advanced → Space Switch panel."
            ),
            category=CATEGORY_RIG_CONTROLS,
            status=STATUS_SUGGESTION,
            impact=4,
            effort=2,
        ))
    return tasks


# ── Master check list ─────────────────────────────────────────
# Ordered: most impactful / most likely to have results first.

ALL_CHECKS = (
    check_twist_bones,
    check_mixamo_bone_names,
    check_rig_validator,
    check_weight_quality,
    check_unweighted_vertices,
    check_face_rig,
    check_ik_pole_targets,
    check_vrchat_performance,
    check_physbone_hair,
    check_space_switch_missing,
)
